# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featuredimage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
