# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_featuredimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostedBy', models.CharField(max_length=100)),
                ('BlogTitle', models.CharField(max_length=200)),
                ('BlogDescription', models.TextField()),
                ('BlogImage', models.ImageField(upload_to='media')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
